name: flutter_codal
description: Coding Runner

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  # assets:
  #   - assets/

  fonts:
    - family: Spoqa
      fonts:
        - asset: fonts/spoqa/SpoqaHanSansNeo-Thin.ttf
          weight: 100
        - asset: fonts/spoqa/SpoqaHanSansNeo-Light.ttf
          weight: 300
        - asset: fonts/spoqa/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: fonts/spoqa/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: fonts/spoqa/SpoqaHanSansNeo-Bold.ttf
          weight: 700
