name: flutter_codal
description: Coding Runner

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  freezed_annotation: ^2.0.1

  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

  # flutter pub run build_runner watch --delete-conflicting-outputs
  freezed: ^2.0.2
  build_runner:
  # .g.dart dependency
  json_serializable:

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/svg/light/
    - assets/svg/dark/
    - assets/svg/light/bottom_nav/
    - assets/svg/dark/bottom_nav/
    - assets/png/
    - assets/png/light/
    - assets/png/dark/

  fonts:
    - family: Spoqa
      fonts:
        - asset: fonts/spoqa/SpoqaHanSansNeo-Thin.ttf
          weight: 100
        - asset: fonts/spoqa/SpoqaHanSansNeo-Light.ttf
          weight: 300
        - asset: fonts/spoqa/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: fonts/spoqa/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: fonts/spoqa/SpoqaHanSansNeo-Bold.ttf
          weight: 700
